/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const ChapterTag = IDL.Variant({
  'strong' : IDL.Null,
  'weakTag' : IDL.Null,
  'neutral' : IDL.Null,
});
export const ChapterStatus = IDL.Variant({
  'pending' : IDL.Null,
  'completed' : IDL.Null,
});
export const Subject = IDL.Variant({
  'maths' : IDL.Null,
  'chemistry' : IDL.Null,
  'physics' : IDL.Null,
});
export const Chapter = IDL.Record({
  'id' : IDL.Nat,
  'tag' : ChapterTag,
  'status' : ChapterStatus,
  'mistakeCount' : IDL.Nat,
  'subject' : Subject,
  'pyqsDone' : IDL.Nat,
  'name' : IDL.Text,
});
export const MistakeType = IDL.Variant({
  'concept' : IDL.Null,
  'silly' : IDL.Null,
  'formula' : IDL.Null,
});
export const Mistake = IDL.Record({
  'id' : IDL.Nat,
  'repeatCount' : IDL.Nat,
  'subject' : Subject,
  'date' : IDL.Text,
  'mistakeType' : MistakeType,
  'description' : IDL.Text,
  'chapterName' : IDL.Text,
});
export const Time = IDL.Int;
export const PYQEntry = IDL.Record({
  'id' : IDL.Nat,
  'startTime' : Time,
  'subject' : Subject,
  'endTime' : Time,
  'date' : IDL.Text,
  'completed' : IDL.Nat,
  'correct' : IDL.Nat,
  'target' : IDL.Nat,
  'wrong' : IDL.Nat,
});
export const StudySession = IDL.Record({
  'id' : IDL.Nat,
  'date' : IDL.Text,
  'durationSeconds' : IDL.Nat,
  'notes' : IDL.Text,
});
export const DailyRecord = IDL.Record({
  'goalMet' : IDL.Bool,
  'date' : IDL.Text,
  'studySeconds' : IDL.Nat,
  'totalPYQs' : IDL.Nat,
});
export const ExamConfig = IDL.Record({
  'weeklyGoal' : IDL.Nat,
  'examDate' : Time,
  'examName' : IDL.Text,
  'dailyPYQGoal' : IDL.Nat,
});

export const idlService = IDL.Service({
  'createChapter' : IDL.Func([Chapter], [IDL.Nat], []),
  'createMistake' : IDL.Func([Mistake], [IDL.Nat], []),
  'createPYQEntry' : IDL.Func([PYQEntry], [IDL.Nat], []),
  'createStudySession' : IDL.Func([StudySession], [IDL.Nat], []),
  'deleteChapter' : IDL.Func([IDL.Nat], [], []),
  'deleteMistake' : IDL.Func([IDL.Nat], [], []),
  'deletePYQEntry' : IDL.Func([IDL.Nat], [], []),
  'deleteStudySession' : IDL.Func([IDL.Nat], [], []),
  'getAllDailyRecords' : IDL.Func([], [IDL.Vec(DailyRecord)], ['query']),
  'getChapter' : IDL.Func([IDL.Nat], [Chapter], ['query']),
  'getDailyRecord' : IDL.Func([IDL.Text], [DailyRecord], ['query']),
  'getExamConfig' : IDL.Func([IDL.Text], [ExamConfig], ['query']),
  'getMistake' : IDL.Func([IDL.Nat], [Mistake], ['query']),
  'getPYQEntry' : IDL.Func([IDL.Nat], [PYQEntry], ['query']),
  'getStudySession' : IDL.Func([IDL.Nat], [StudySession], ['query']),
  'incrementMistakeRepeatCount' : IDL.Func([IDL.Nat], [], []),
  'setExamConfig' : IDL.Func([IDL.Text, ExamConfig], [], []),
  'updateChapter' : IDL.Func([IDL.Nat, Chapter], [], []),
  'updatePYQEntry' : IDL.Func([IDL.Nat, PYQEntry], [], []),
  'updateStudySession' : IDL.Func([IDL.Nat, StudySession], [], []),
  'upsertDailyRecord' : IDL.Func([DailyRecord], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const ChapterTag = IDL.Variant({
    'strong' : IDL.Null,
    'weakTag' : IDL.Null,
    'neutral' : IDL.Null,
  });
  const ChapterStatus = IDL.Variant({
    'pending' : IDL.Null,
    'completed' : IDL.Null,
  });
  const Subject = IDL.Variant({
    'maths' : IDL.Null,
    'chemistry' : IDL.Null,
    'physics' : IDL.Null,
  });
  const Chapter = IDL.Record({
    'id' : IDL.Nat,
    'tag' : ChapterTag,
    'status' : ChapterStatus,
    'mistakeCount' : IDL.Nat,
    'subject' : Subject,
    'pyqsDone' : IDL.Nat,
    'name' : IDL.Text,
  });
  const MistakeType = IDL.Variant({
    'concept' : IDL.Null,
    'silly' : IDL.Null,
    'formula' : IDL.Null,
  });
  const Mistake = IDL.Record({
    'id' : IDL.Nat,
    'repeatCount' : IDL.Nat,
    'subject' : Subject,
    'date' : IDL.Text,
    'mistakeType' : MistakeType,
    'description' : IDL.Text,
    'chapterName' : IDL.Text,
  });
  const Time = IDL.Int;
  const PYQEntry = IDL.Record({
    'id' : IDL.Nat,
    'startTime' : Time,
    'subject' : Subject,
    'endTime' : Time,
    'date' : IDL.Text,
    'completed' : IDL.Nat,
    'correct' : IDL.Nat,
    'target' : IDL.Nat,
    'wrong' : IDL.Nat,
  });
  const StudySession = IDL.Record({
    'id' : IDL.Nat,
    'date' : IDL.Text,
    'durationSeconds' : IDL.Nat,
    'notes' : IDL.Text,
  });
  const DailyRecord = IDL.Record({
    'goalMet' : IDL.Bool,
    'date' : IDL.Text,
    'studySeconds' : IDL.Nat,
    'totalPYQs' : IDL.Nat,
  });
  const ExamConfig = IDL.Record({
    'weeklyGoal' : IDL.Nat,
    'examDate' : Time,
    'examName' : IDL.Text,
    'dailyPYQGoal' : IDL.Nat,
  });
  
  return IDL.Service({
    'createChapter' : IDL.Func([Chapter], [IDL.Nat], []),
    'createMistake' : IDL.Func([Mistake], [IDL.Nat], []),
    'createPYQEntry' : IDL.Func([PYQEntry], [IDL.Nat], []),
    'createStudySession' : IDL.Func([StudySession], [IDL.Nat], []),
    'deleteChapter' : IDL.Func([IDL.Nat], [], []),
    'deleteMistake' : IDL.Func([IDL.Nat], [], []),
    'deletePYQEntry' : IDL.Func([IDL.Nat], [], []),
    'deleteStudySession' : IDL.Func([IDL.Nat], [], []),
    'getAllDailyRecords' : IDL.Func([], [IDL.Vec(DailyRecord)], ['query']),
    'getChapter' : IDL.Func([IDL.Nat], [Chapter], ['query']),
    'getDailyRecord' : IDL.Func([IDL.Text], [DailyRecord], ['query']),
    'getExamConfig' : IDL.Func([IDL.Text], [ExamConfig], ['query']),
    'getMistake' : IDL.Func([IDL.Nat], [Mistake], ['query']),
    'getPYQEntry' : IDL.Func([IDL.Nat], [PYQEntry], ['query']),
    'getStudySession' : IDL.Func([IDL.Nat], [StudySession], ['query']),
    'incrementMistakeRepeatCount' : IDL.Func([IDL.Nat], [], []),
    'setExamConfig' : IDL.Func([IDL.Text, ExamConfig], [], []),
    'updateChapter' : IDL.Func([IDL.Nat, Chapter], [], []),
    'updatePYQEntry' : IDL.Func([IDL.Nat, PYQEntry], [], []),
    'updateStudySession' : IDL.Func([IDL.Nat, StudySession], [], []),
    'upsertDailyRecord' : IDL.Func([DailyRecord], [], []),
  });
};

export const init = ({ IDL }) => { return []; };