/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Chapter {
  'id' : bigint,
  'tag' : ChapterTag,
  'status' : ChapterStatus,
  'mistakeCount' : bigint,
  'subject' : Subject,
  'pyqsDone' : bigint,
  'name' : string,
}
export type ChapterStatus = { 'pending' : null } |
  { 'completed' : null };
export type ChapterTag = { 'strong' : null } |
  { 'weakTag' : null } |
  { 'neutral' : null };
export interface DailyRecord {
  'goalMet' : boolean,
  'date' : string,
  'studySeconds' : bigint,
  'totalPYQs' : bigint,
}
export interface ExamConfig {
  'weeklyGoal' : bigint,
  'examDate' : Time,
  'examName' : string,
  'dailyPYQGoal' : bigint,
}
export interface Mistake {
  'id' : bigint,
  'repeatCount' : bigint,
  'subject' : Subject,
  'date' : string,
  'mistakeType' : MistakeType,
  'description' : string,
  'chapterName' : string,
}
export type MistakeType = { 'concept' : null } |
  { 'silly' : null } |
  { 'formula' : null };
export interface PYQEntry {
  'id' : bigint,
  'startTime' : Time,
  'subject' : Subject,
  'endTime' : Time,
  'date' : string,
  'completed' : bigint,
  'correct' : bigint,
  'target' : bigint,
  'wrong' : bigint,
}
export interface StudySession {
  'id' : bigint,
  'date' : string,
  'durationSeconds' : bigint,
  'notes' : string,
}
export type Subject = { 'maths' : null } |
  { 'chemistry' : null } |
  { 'physics' : null };
export type Time = bigint;
export interface _SERVICE {
  'createChapter' : ActorMethod<[Chapter], bigint>,
  'createMistake' : ActorMethod<[Mistake], bigint>,
  'createPYQEntry' : ActorMethod<[PYQEntry], bigint>,
  'createStudySession' : ActorMethod<[StudySession], bigint>,
  'deleteChapter' : ActorMethod<[bigint], undefined>,
  'deleteMistake' : ActorMethod<[bigint], undefined>,
  'deletePYQEntry' : ActorMethod<[bigint], undefined>,
  'deleteStudySession' : ActorMethod<[bigint], undefined>,
  'getAllDailyRecords' : ActorMethod<[], Array<DailyRecord>>,
  'getChapter' : ActorMethod<[bigint], Chapter>,
  'getDailyRecord' : ActorMethod<[string], DailyRecord>,
  'getExamConfig' : ActorMethod<[string], ExamConfig>,
  'getMistake' : ActorMethod<[bigint], Mistake>,
  'getPYQEntry' : ActorMethod<[bigint], PYQEntry>,
  'getStudySession' : ActorMethod<[bigint], StudySession>,
  'incrementMistakeRepeatCount' : ActorMethod<[bigint], undefined>,
  'setExamConfig' : ActorMethod<[string, ExamConfig], undefined>,
  'updateChapter' : ActorMethod<[bigint, Chapter], undefined>,
  'updatePYQEntry' : ActorMethod<[bigint, PYQEntry], undefined>,
  'updateStudySession' : ActorMethod<[bigint, StudySession], undefined>,
  'upsertDailyRecord' : ActorMethod<[DailyRecord], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];