/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface ExamConfig {
    weeklyGoal: bigint;
    examDate: Time;
    examName: string;
    dailyPYQGoal: bigint;
}
export type Time = bigint;
export interface Mistake {
    id: bigint;
    repeatCount: bigint;
    subject: Subject;
    date: string;
    mistakeType: MistakeType;
    description: string;
    chapterName: string;
}
export interface StudySession {
    id: bigint;
    date: string;
    durationSeconds: bigint;
    notes: string;
}
export interface DailyRecord {
    goalMet: boolean;
    date: string;
    studySeconds: bigint;
    totalPYQs: bigint;
}
export interface PYQEntry {
    id: bigint;
    startTime: Time;
    subject: Subject;
    endTime: Time;
    date: string;
    completed: bigint;
    correct: bigint;
    target: bigint;
    wrong: bigint;
}
export interface Chapter {
    id: bigint;
    tag: ChapterTag;
    status: ChapterStatus;
    mistakeCount: bigint;
    subject: Subject;
    pyqsDone: bigint;
    name: string;
}
export enum ChapterStatus {
    pending = "pending",
    completed = "completed"
}
export enum ChapterTag {
    strong = "strong",
    weakTag = "weakTag",
    neutral = "neutral"
}
export enum MistakeType {
    concept = "concept",
    silly = "silly",
    formula = "formula"
}
export enum Subject {
    maths = "maths",
    chemistry = "chemistry",
    physics = "physics"
}
export interface backendInterface {
    createChapter(chapter: Chapter): Promise<bigint>;
    createMistake(mistake: Mistake): Promise<bigint>;
    createPYQEntry(entry: PYQEntry): Promise<bigint>;
    createStudySession(session: StudySession): Promise<bigint>;
    deleteChapter(id: bigint): Promise<void>;
    deleteMistake(id: bigint): Promise<void>;
    deletePYQEntry(id: bigint): Promise<void>;
    deleteStudySession(id: bigint): Promise<void>;
    getAllDailyRecords(): Promise<Array<DailyRecord>>;
    getChapter(id: bigint): Promise<Chapter>;
    getDailyRecord(date: string): Promise<DailyRecord>;
    getExamConfig(name: string): Promise<ExamConfig>;
    getMistake(id: bigint): Promise<Mistake>;
    getPYQEntry(id: bigint): Promise<PYQEntry>;
    getStudySession(id: bigint): Promise<StudySession>;
    incrementMistakeRepeatCount(id: bigint): Promise<void>;
    setExamConfig(name: string, config: ExamConfig): Promise<void>;
    updateChapter(id: bigint, chapter: Chapter): Promise<void>;
    updatePYQEntry(id: bigint, entry: PYQEntry): Promise<void>;
    updateStudySession(id: bigint, session: StudySession): Promise<void>;
    upsertDailyRecord(record: DailyRecord): Promise<void>;
}
import type { Chapter as _Chapter, ChapterStatus as _ChapterStatus, ChapterTag as _ChapterTag, Mistake as _Mistake, MistakeType as _MistakeType, PYQEntry as _PYQEntry, Subject as _Subject, Time as _Time } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async createChapter(arg0: Chapter): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createChapter(to_candid_Chapter_n1(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createChapter(to_candid_Chapter_n1(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async createMistake(arg0: Mistake): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createMistake(to_candid_Mistake_n9(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createMistake(to_candid_Mistake_n9(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async createPYQEntry(arg0: PYQEntry): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createPYQEntry(to_candid_PYQEntry_n13(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createPYQEntry(to_candid_PYQEntry_n13(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async createStudySession(arg0: StudySession): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createStudySession(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createStudySession(arg0);
            return result;
        }
    }
    async deleteChapter(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteChapter(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteChapter(arg0);
            return result;
        }
    }
    async deleteMistake(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteMistake(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteMistake(arg0);
            return result;
        }
    }
    async deletePYQEntry(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deletePYQEntry(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deletePYQEntry(arg0);
            return result;
        }
    }
    async deleteStudySession(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteStudySession(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteStudySession(arg0);
            return result;
        }
    }
    async getAllDailyRecords(): Promise<Array<DailyRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllDailyRecords();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllDailyRecords();
            return result;
        }
    }
    async getChapter(arg0: bigint): Promise<Chapter> {
        if (this.processError) {
            try {
                const result = await this.actor.getChapter(arg0);
                return from_candid_Chapter_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getChapter(arg0);
            return from_candid_Chapter_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDailyRecord(arg0: string): Promise<DailyRecord> {
        if (this.processError) {
            try {
                const result = await this.actor.getDailyRecord(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDailyRecord(arg0);
            return result;
        }
    }
    async getExamConfig(arg0: string): Promise<ExamConfig> {
        if (this.processError) {
            try {
                const result = await this.actor.getExamConfig(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getExamConfig(arg0);
            return result;
        }
    }
    async getMistake(arg0: bigint): Promise<Mistake> {
        if (this.processError) {
            try {
                const result = await this.actor.getMistake(arg0);
                return from_candid_Mistake_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMistake(arg0);
            return from_candid_Mistake_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPYQEntry(arg0: bigint): Promise<PYQEntry> {
        if (this.processError) {
            try {
                const result = await this.actor.getPYQEntry(arg0);
                return from_candid_PYQEntry_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPYQEntry(arg0);
            return from_candid_PYQEntry_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async getStudySession(arg0: bigint): Promise<StudySession> {
        if (this.processError) {
            try {
                const result = await this.actor.getStudySession(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStudySession(arg0);
            return result;
        }
    }
    async incrementMistakeRepeatCount(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.incrementMistakeRepeatCount(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.incrementMistakeRepeatCount(arg0);
            return result;
        }
    }
    async setExamConfig(arg0: string, arg1: ExamConfig): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setExamConfig(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setExamConfig(arg0, arg1);
            return result;
        }
    }
    async updateChapter(arg0: bigint, arg1: Chapter): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateChapter(arg0, to_candid_Chapter_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateChapter(arg0, to_candid_Chapter_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updatePYQEntry(arg0: bigint, arg1: PYQEntry): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updatePYQEntry(arg0, to_candid_PYQEntry_n13(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updatePYQEntry(arg0, to_candid_PYQEntry_n13(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateStudySession(arg0: bigint, arg1: StudySession): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateStudySession(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateStudySession(arg0, arg1);
            return result;
        }
    }
    async upsertDailyRecord(arg0: DailyRecord): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.upsertDailyRecord(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.upsertDailyRecord(arg0);
            return result;
        }
    }
}
function from_candid_ChapterStatus_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ChapterStatus): ChapterStatus {
    return from_candid_variant_n20(_uploadFile, _downloadFile, value);
}
function from_candid_ChapterTag_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ChapterTag): ChapterTag {
    return from_candid_variant_n18(_uploadFile, _downloadFile, value);
}
function from_candid_Chapter_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Chapter): Chapter {
    return from_candid_record_n16(_uploadFile, _downloadFile, value);
}
function from_candid_MistakeType_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MistakeType): MistakeType {
    return from_candid_variant_n26(_uploadFile, _downloadFile, value);
}
function from_candid_Mistake_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Mistake): Mistake {
    return from_candid_record_n24(_uploadFile, _downloadFile, value);
}
function from_candid_PYQEntry_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PYQEntry): PYQEntry {
    return from_candid_record_n28(_uploadFile, _downloadFile, value);
}
function from_candid_Subject_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Subject): Subject {
    return from_candid_variant_n22(_uploadFile, _downloadFile, value);
}
function from_candid_record_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    tag: _ChapterTag;
    status: _ChapterStatus;
    mistakeCount: bigint;
    subject: _Subject;
    pyqsDone: bigint;
    name: string;
}): {
    id: bigint;
    tag: ChapterTag;
    status: ChapterStatus;
    mistakeCount: bigint;
    subject: Subject;
    pyqsDone: bigint;
    name: string;
} {
    return {
        id: value.id,
        tag: from_candid_ChapterTag_n17(_uploadFile, _downloadFile, value.tag),
        status: from_candid_ChapterStatus_n19(_uploadFile, _downloadFile, value.status),
        mistakeCount: value.mistakeCount,
        subject: from_candid_Subject_n21(_uploadFile, _downloadFile, value.subject),
        pyqsDone: value.pyqsDone,
        name: value.name
    };
}
function from_candid_record_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    repeatCount: bigint;
    subject: _Subject;
    date: string;
    mistakeType: _MistakeType;
    description: string;
    chapterName: string;
}): {
    id: bigint;
    repeatCount: bigint;
    subject: Subject;
    date: string;
    mistakeType: MistakeType;
    description: string;
    chapterName: string;
} {
    return {
        id: value.id,
        repeatCount: value.repeatCount,
        subject: from_candid_Subject_n21(_uploadFile, _downloadFile, value.subject),
        date: value.date,
        mistakeType: from_candid_MistakeType_n25(_uploadFile, _downloadFile, value.mistakeType),
        description: value.description,
        chapterName: value.chapterName
    };
}
function from_candid_record_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    startTime: _Time;
    subject: _Subject;
    endTime: _Time;
    date: string;
    completed: bigint;
    correct: bigint;
    target: bigint;
    wrong: bigint;
}): {
    id: bigint;
    startTime: Time;
    subject: Subject;
    endTime: Time;
    date: string;
    completed: bigint;
    correct: bigint;
    target: bigint;
    wrong: bigint;
} {
    return {
        id: value.id,
        startTime: value.startTime,
        subject: from_candid_Subject_n21(_uploadFile, _downloadFile, value.subject),
        endTime: value.endTime,
        date: value.date,
        completed: value.completed,
        correct: value.correct,
        target: value.target,
        wrong: value.wrong
    };
}
function from_candid_variant_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    strong: null;
} | {
    weakTag: null;
} | {
    neutral: null;
}): ChapterTag {
    return "strong" in value ? ChapterTag.strong : "weakTag" in value ? ChapterTag.weakTag : "neutral" in value ? ChapterTag.neutral : value;
}
function from_candid_variant_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    completed: null;
}): ChapterStatus {
    return "pending" in value ? ChapterStatus.pending : "completed" in value ? ChapterStatus.completed : value;
}
function from_candid_variant_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    maths: null;
} | {
    chemistry: null;
} | {
    physics: null;
}): Subject {
    return "maths" in value ? Subject.maths : "chemistry" in value ? Subject.chemistry : "physics" in value ? Subject.physics : value;
}
function from_candid_variant_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    concept: null;
} | {
    silly: null;
} | {
    formula: null;
}): MistakeType {
    return "concept" in value ? MistakeType.concept : "silly" in value ? MistakeType.silly : "formula" in value ? MistakeType.formula : value;
}
function to_candid_ChapterStatus_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ChapterStatus): _ChapterStatus {
    return to_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function to_candid_ChapterTag_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ChapterTag): _ChapterTag {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_Chapter_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Chapter): _Chapter {
    return to_candid_record_n2(_uploadFile, _downloadFile, value);
}
function to_candid_MistakeType_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: MistakeType): _MistakeType {
    return to_candid_variant_n12(_uploadFile, _downloadFile, value);
}
function to_candid_Mistake_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Mistake): _Mistake {
    return to_candid_record_n10(_uploadFile, _downloadFile, value);
}
function to_candid_PYQEntry_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PYQEntry): _PYQEntry {
    return to_candid_record_n14(_uploadFile, _downloadFile, value);
}
function to_candid_Subject_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Subject): _Subject {
    return to_candid_variant_n8(_uploadFile, _downloadFile, value);
}
function to_candid_record_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    repeatCount: bigint;
    subject: Subject;
    date: string;
    mistakeType: MistakeType;
    description: string;
    chapterName: string;
}): {
    id: bigint;
    repeatCount: bigint;
    subject: _Subject;
    date: string;
    mistakeType: _MistakeType;
    description: string;
    chapterName: string;
} {
    return {
        id: value.id,
        repeatCount: value.repeatCount,
        subject: to_candid_Subject_n7(_uploadFile, _downloadFile, value.subject),
        date: value.date,
        mistakeType: to_candid_MistakeType_n11(_uploadFile, _downloadFile, value.mistakeType),
        description: value.description,
        chapterName: value.chapterName
    };
}
function to_candid_record_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    startTime: Time;
    subject: Subject;
    endTime: Time;
    date: string;
    completed: bigint;
    correct: bigint;
    target: bigint;
    wrong: bigint;
}): {
    id: bigint;
    startTime: _Time;
    subject: _Subject;
    endTime: _Time;
    date: string;
    completed: bigint;
    correct: bigint;
    target: bigint;
    wrong: bigint;
} {
    return {
        id: value.id,
        startTime: value.startTime,
        subject: to_candid_Subject_n7(_uploadFile, _downloadFile, value.subject),
        endTime: value.endTime,
        date: value.date,
        completed: value.completed,
        correct: value.correct,
        target: value.target,
        wrong: value.wrong
    };
}
function to_candid_record_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    tag: ChapterTag;
    status: ChapterStatus;
    mistakeCount: bigint;
    subject: Subject;
    pyqsDone: bigint;
    name: string;
}): {
    id: bigint;
    tag: _ChapterTag;
    status: _ChapterStatus;
    mistakeCount: bigint;
    subject: _Subject;
    pyqsDone: bigint;
    name: string;
} {
    return {
        id: value.id,
        tag: to_candid_ChapterTag_n3(_uploadFile, _downloadFile, value.tag),
        status: to_candid_ChapterStatus_n5(_uploadFile, _downloadFile, value.status),
        mistakeCount: value.mistakeCount,
        subject: to_candid_Subject_n7(_uploadFile, _downloadFile, value.subject),
        pyqsDone: value.pyqsDone,
        name: value.name
    };
}
function to_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: MistakeType): {
    concept: null;
} | {
    silly: null;
} | {
    formula: null;
} {
    return value == MistakeType.concept ? {
        concept: null
    } : value == MistakeType.silly ? {
        silly: null
    } : value == MistakeType.formula ? {
        formula: null
    } : value;
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ChapterTag): {
    strong: null;
} | {
    weakTag: null;
} | {
    neutral: null;
} {
    return value == ChapterTag.strong ? {
        strong: null
    } : value == ChapterTag.weakTag ? {
        weakTag: null
    } : value == ChapterTag.neutral ? {
        neutral: null
    } : value;
}
function to_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ChapterStatus): {
    pending: null;
} | {
    completed: null;
} {
    return value == ChapterStatus.pending ? {
        pending: null
    } : value == ChapterStatus.completed ? {
        completed: null
    } : value;
}
function to_candid_variant_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Subject): {
    maths: null;
} | {
    chemistry: null;
} | {
    physics: null;
} {
    return value == Subject.maths ? {
        maths: null
    } : value == Subject.chemistry ? {
        chemistry: null
    } : value == Subject.physics ? {
        physics: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
